In [94]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 

In [8]:
col_names = ['pregnant','glucose','bp','skin','insulin','bmi','pedigree','age','label']
data = pd.read_csv('pima-indians-diabetes.csv', names = col_names)

In [9]:
data.head()

pregnant  glucose  bp  skin  insulin   bmi  pedigree  age  label
0         6      148  72    35        0  33.6     0.627   50      1
1         1       85  66    29        0  26.6     0.351   31      0
2         8      183  64     0        0  23.3     0.672   32      1
3         1       89  66    23       94  28.1     0.167   21      0
4         0      137  40    35      168  43.1     2.288   33      1

In [10]:
data.sample(10)

pregnant  glucose  bp  skin  insulin   bmi  pedigree  age  label
707         2      127  46    21      335  34.4     0.176   22      0
82          7       83  78    26       71  29.3     0.767   36      0
116         5      124  74     0        0  34.0     0.220   38      1
157         1      109  56    21      135  25.2     0.833   23      0
312         2      155  74    17       96  26.6     0.433   27      1
173         1       79  60    42       48  43.5     0.678   23      0
430         2       99   0     0        0  22.2     0.108   23      0
527         3      116  74    15      105  26.3     0.107   24      0
9           8      125  96     0        0   0.0     0.232   54      1
72         13      126  90     0        0  43.4     0.583   42      1

In [11]:
X = data.drop(["label"] , axis = 1 )
y = data ['label']

In [13]:
from sklearn.model_selection import train_test_split as tts

In [80]:
X_train , X_test , y_train , y_test = tts ( X , y , test_size = .25 , random_state = 95)

In [81]:
print ( X_train.shape , X_test.shape , y_train.shape , y_test.shape )

(576, 8) (192, 8) (576,) (192,)


In [82]:
X_train.head()

pregnant  glucose  bp  skin  insulin   bmi  pedigree  age
238         9      164  84    21        0  30.8     0.831   32
258         1      193  50    16      375  25.9     0.655   24
108         3       83  58    31       18  34.3     0.336   25
354         3       90  78     0        0  42.7     0.559   21
595         0      188  82    14      185  32.0     0.682   22

In [83]:
y_train.head()

238    1
258    0
108    0
354    0
595    1
Name: label, dtype: int64

In [84]:
from sklearn.neighbors import KNeighborsClassifier as knc
KNN_model = knc(n_neighbors=2)
print(KNN_model)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=2, p=2,
                     weights='uniform')


In [85]:
KNN_model.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=2, p=2,
                     weights='uniform')

temp = X_test[:10]
temp['label'] = y_test[:10]
temp['predicted'] = KNN_model.predict( X_train[:10] )
temp



In [86]:
predicted = KNN_model.predict( X_test )
original  = y_test.values
wrong = 0
for i in range(len(predicted)):
    if predicted[i] != original[i]:
        wrong = wrong + 1
print(wrong)        

58


In [87]:
a,b=130,160
predicted = KNN_model.predict( X_test )
print(predicted[a:b])
print(y_test[a:b].values)
  

[0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0]
[0 1 0 1 1 1 0 0 1 0 0 1 1 1 1 0 0 0 0 0 0 1 0 1 1 1 0 0 0 1]


In [88]:
KNN_model.score(X_test,y_test)

0.6979166666666666

In [93]:
predicted.shape

(192,)

In [89]:
X_test.head()

pregnant  glucose  bp  skin  insulin   bmi  pedigree  age
435         0      141   0     0        0  42.4     0.205   29
615         3      106  72     0        0  25.8     0.207   27
598         1      173  74     0        0  36.8     0.088   38
195         5      158  84    41      210  39.4     0.395   29
599         1      109  38    18      120  23.1     0.407   26

In [90]:
y_test.head()

435    1
615    0
598    1
195    1
599    0
Name: label, dtype: int64

In [91]:
from sklearn.metrics import confusion_matrix as cm
cm(original,predicted)

array([[112,  12],
       [ 46,  22]], dtype=int64)